version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
      - "443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app
    env_file: ./dc.env

  app:
    image: node:latest
    container_name: my-app
    working_dir: /application
    volumes:
      - .:/application
    links:
      - mysql
      - redis
      - mailhog
    ports:
      - "9000"
    entrypoint: ./start_application.sh
    env_file: ./dc.env
    environment:
      "NODE_ENV": "development"

  mysql:
    env_file: ./dc.env
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"